apiVersion: v1
kind: Service
metadata:
  namespace: istio-system
  name: kiali
  labels:
    app: kiali
spec:
  type: NodePort
  selector:
    app: kiali
  ports:
    - port: 20001               
      targetPort: 20001       
      nodePort: 30008   

